- name: Casquette Cayak Actu
  price: 29.99
  slug: casquette
  sku: CSQ
  image: http://www.cayakactu.fr/images/shop/casquettes.jpg

- name: Tee shirt Léa Jamelot
  price: 29.99
  slug: teeshirt-lea-jamelot
  sku: TSLJ
  image: http://www.cayakactu.fr/images/shop/teeshirt-lea-jamelot.jpg

- name: Tee shirt Sarah Troël
  price: 29.99
  slug: teeshirt-sarah-troel
  sku: TSST
  image: http://www.cayakactu.fr/images/shop/teeshirt-sarah-troel.jpg

- name: Tee shirt Maxime Beaumont
  price: 29.99
  slug: teeshirt-maxime-beaumont
  sku: TSMB
  image: http://www.cayakactu.fr/images/shop/teeshirt-maxime-beaumont.jpg

- name: Tee shirt Sarah guyot
  price: 29.99
  slug: teeshirt-sarah-guyot
  sku: TSSG
  image: http://www.cayakactu.fr/images/shop/teeshirt-sarah-guyot.jpg
