- name: Casquette Cayak Actu
  price: 29.99
  slug: casquette
  sku: CSQ
  image: http://www.cayakactu.fr/images/shop/casquettes.png

- name: Tatoo Cayak Actu
  description: "Avec notre partenaire tatouagetemporaire.com"
  price: 9.99
  slug: tatoo-cayak-actu
  sku: TTCA
  image: http://www.cayakactu.fr/images/shop/tatoo-cayak-actu.jpg

- name: Tee shirt DTN
  price: 29.99
  slug: teeshirt-dtn
  sku: TSDTN
  image: http://www.cayakactu.fr/images/shop/teeshirt-dtn.jpg

- name: Tee shirt K4 dames
  price: 29.99
  slug: teeshirt-k4d
  sku: TSK4D
  image: http://www.cayakactu.fr/images/shop/teeshirt-k4d.jpg

- name: Tee shirt Léa Jamelot
  price: 29.99
  slug: teeshirt-lea-jamelot
  sku: TSLJ
  image: http://www.cayakactu.fr/images/shop/teeshirt-lea-jamelot.jpg

- name: Tee shirt Sarah Troël
  price: 29.99
  slug: teeshirt-sarah-troel
  sku: TSST
  image: http://www.cayakactu.fr/images/shop/teeshirt-sarah-troel.jpg


- name: Tee shirt Adrien Bart
  price: 29.99
  slug: teeshirt-adrien-bart
  sku: TSAB
  image: http://www.cayakactu.fr/images/shop/teeshirt-adrien-bart.jpg

- name: Tee shirt Maxime Beaumont
  price: 29.99
  slug: teeshirt-maxime-beaumont
  sku: TSMB
  image: http://www.cayakactu.fr/images/shop/teeshirt-maxime-beaumont.jpg

- name: Tee shirt Sarah Guyot
  price: 29.99
  slug: teeshirt-sarah-guyot
  sku: TSSG
  image: http://www.cayakactu.fr/images/shop/teeshirt-sarah-guyot.jpg
